### ISSUE TITLE
Citation-adding suggestion

### ISSUE THREAD

**Issue by limanwang** [HCPLab-SYSU/Embodied_AI_Paper_List#11]
Hello, thank you for sharing this nice survey, here are the citation-adding suggestions:

LLM-SAP: Large Language Model Situational Awareness-Based Planning
ICME 2024 workshop paper, https://vista-h.github.io/MML4SG_2024/papers/wang2024llm.pdf

Deformable object manipulation in caregiving scenarios: A review
MDPI Machines 2023, 11(11), 1013; https://doi.org/10.3390/machines11111013

Best regards,
Liman

**Comment by HCPLab-SYSU** [comment]
Thanks you for your suggestion. We have added them in the project!

**Comment by limanwang** [comment]
Thank you for adding the references. However, I noticed that the citation link for the paper "Deformable Object Manipulation in Caregiving Scenarios: A Review" is incorrect. The correct link is the one I provided earlier.
