### ISSUE TITLE
Content Layout Suggestion

### ISSUE THREAD

**Issue by bohaocheung** [HCPLab-SYSU/Embodied_AI_Paper_List#12]
Thanks for publish & share this paper list with us! There's a little suggestion for the content layout. It's better to arrange papers in chronological order from newest to oldest and the same way to update papers. That will be convenient for readers to focus on the works on the leading edge!!! By the way, the `diffusion policy` is hot recently and hope to meet more relevant papers!!!

**Comment by HCPLab-SYSU** [comment]
Thanks a lot for this good suggestion! We will update the project soon!
