### ISSUE TITLE
Citation Address Issue

### ISSUE THREAD

**Issue by limanwang** [HCPLab-SYSU/Embodied_AI_Paper_List#13]
Thank you for adding the references. However, I noticed that the citation link for the paper "Deformable Object Manipulation in Caregiving Scenarios: A Review" is incorrect. The correct link is the one I provided earlier.
MDPI Machines 2023, 11(11), 1013; https://doi.org/10.3390/machines11111013

Best regards,
Liman

**Comment by HCPLab-SYSU** [comment]
Thank you for pointing out this issue. We have corrected it!
