### ISSUE TITLE
Adding recent papers

### ISSUE THREAD

**Issue by chen-judge** [HCPLab-SYSU/Embodied_AI_Paper_List#15]
Thank you for your efforts! I would like to share our two papers about the VLN task. If you find them useful, please consider citing these papers, thanks!

MapGPT: Map-Guided Prompting with Adaptive Path Planning for Vision-and-Language Navigation, ACL, 2024.
Jiaqi Chen, Bingqian Lin, Ran Xu, Zhenhua Chai, Xiaodan Liang, Kwan-Yee K. Wong.
[[page]](https://chen-judge.github.io/MapGPT/)

NavCoT: Boosting LLM-Based Vision-and-Language Navigation via Learning Disentangled Reasoning, ArXiv, 2024.
Bingqian Lin, Yunshuang Nie, Ziming Wei, Jiaqi Chen, Shikui Ma, Jianhua Han, Hang Xu, Xiaojun Chang, Xiaodan Liang.
[[page]](https://arxiv.org/abs/2403.07376)

**Comment by HCPLab-SYSU** [comment]
Thanks for your suggestion! We have added these two papers.
