### ISSUE TITLE
New paper adding suggestions

### ISSUE THREAD

**Issue by SiyuanHuang95** [HCPLab-SYSU/Embodied_AI_Paper_List#7]
Hi, thanks for sharing this repo, I would like to self-prompt some papers in the Embodied AI, you can select some when you find them useful.

## Manipulation-Related:

- [Instruct2act: Mapping multi-modality instructions to robotic actions with large language model](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=QNkS4KEAAAAJ&citation_for_view=QNkS4KEAAAAJ:M3NEmzRMIkIC)
S Huang, Z Jiang, H Dong, Y Qiao, P Gao, H Li
arXiv preprint arXiv:2305.11176

- [Manipvqa: Injecting robotic affordance and physically grounded information into multi-modal large language models](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=QNkS4KEAAAAJ&citation_for_view=QNkS4KEAAAAJ:ns9cj8rnVeAC)
S Huang, I Ponomarenko, Z Jiang, X Li, X Hu, P Gao, H Li, H Dong
IROS2024

- [A3VLM: Actionable Articulation-Aware Vision Language Model](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=QNkS4KEAAAAJ&citation_for_view=QNkS4KEAAAAJ:RYcK_YlVTxYC)
S Huang, H Chang, Y Liu, Y Zhu, H Dong, P Gao, A Boularias, H Li
arXiv preprint arXiv:2406.07549

## Navigation Related:

- [Bridging zero-shot object navigation and foundation models through pixel-guided navigation skill](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=QNkS4KEAAAAJ&citation_for_view=QNkS4KEAAAAJ:hMod-77fHWUC)
W Cai, S Huang, G Cheng, Y Long, P Gao, C Sun, H Dong
ICRA2024

**Comment by HCPLab-SYSU** [comment]
Thanks a lot for your suggestion! We have added these papers.
